packages:
  - packages/**

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - cypress
  - es5-ext
  - husky
  - nx
  - unrs-resolver

patchedDependencies:
  unplugin-dts: patches/unplugin-dts.patch
